import {StyleSheet} from 'react-native';
import {COLORS} from '../../Colors/Colors';
import {FONT_FAMILY} from '../../Fonts/FONTS';
export const HomeScreenStyle = StyleSheet.create({
  topBarContainerStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 7,
    alignItems: 'center',
  },
  InstagramTextStyle: {
    fontFamily: FONT_FAMILY.LOBSTER_REGULAR,
    fontSize: 20,
    fontWeight: 500,
    color: COLORS.BLACK,
  },
  fontRightContainerStyle: {flexDirection: 'row'},
  fontStyle: {fontSize: 24, color: COLORS.BLACK, marginHorizontal: 10},
  storyContainer: {paddingVertical: 10, paddingHorizontal: 5},
  plusIconStyle: {
    fontSize: 18,
    backgroundColor: COLORS.WHITE,
    color: COLORS.BLUE,
    borderRadius: 100,
  },
  imageViewStyle: {
    width: 68,
    height: 68,
    borderRadius: 100,
    borderWidth: 1.8,
    backgroundColor: COLORS.WHITE,
    borderColor: COLORS.STORY_BACK,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageStyle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    resizeMode: 'cover',
  },
  plusIconContainer: {position: 'absolute', bottom: 15, right: 0, zIndex: 1},
  textStyle: {textAlign: 'center', fontSize: 10},
  storyRootContainer: {marginHorizontal: 4},
  statusRootContainerStyle: {
    flex: 1,
    backgroundColor: COLORS.BLACK,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusLoadingContainerStyle: {
    height: 3,
    width: '95%',
    backgroundColor: 'grey',
    position: 'absolute',
    top: 15,
  },
  statusLoadingInnerViewStyle: {
    height: '100%',
    backgroundColor: COLORS.WHITE,
  },
  statusImageViewStyle: {
    position: 'absolute',
    top: 25,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 15,
  },
  statusImageStyle: {
    width: 35,
    height: 35,
    borderRadius: 17.5,
    resizeMode: 'cover',
  },
  statusNameStyle: {color: COLORS.WHITE, marginHorizontal: 5, fontSize: 12},
  statusTopContainerStyle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    flex: 1,
  },
  closeIconStyle: {fontSize: 20, color: COLORS.WHITE, opacity: 0.6},
  mainStatusImageStyle: {height: 500, width: '100%'},
  textInputContainerStyle: {
    position: 'absolute',
    bottom: 0,
    left: 10,
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
    justifyContent: 'space-around',
  },
  textInputStyle: {
    borderWidth: 0.8,
    borderRadius: 25,
    height: 40,
    width: '85%',
    borderColor: 'white',
    fontSize: 15,
    color: COLORS.WHITE,
    paddingLeft: 20,
  },
  navigationIconStyle: {fontSize: 30, color: COLORS.WHITE, opacity: 0.7},
  postRootContainer: {
    paddingBottom: 10,
    borderBottomColor: 'grey',
    borderBottomWidth: 0.1,
  },
  postInnerContainerStyle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 15,
  },
  postHeaderViewStyle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  personHeaderIconStyle: {width: 40, height: 40, borderRadius: 100},
  postHeaderNameStyle: {
    fontSize: 15,
    fontWeight: 'bold',
    paddingLeft: 5,
    color: COLORS.BLACK,
  },
  verticalDotIconStyle: {fontSize: 20},
  postImageStyle: {height: 350, width: '100%'},
  postBottomConatiner: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
  },
  postBottomIconViewContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    // justifyContent: 'space-between',
    padding: 15,
  },
  postChatIconStyle: {
    fontSize: 20,
    paddingRight: 10,
  },
  postNavigationIconStyle: {
    fontSize: 20,
    paddingRight: 10,
  },
  postBookmarkIconStyle: {fontSize: 20, paddingRight: 8},
  commentsIconPersonStyle: {
    height: 25,
    width: 25,
    borderRadius: 100,
    marginRight: 5,
  },
  commentViewStyle: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  descriptionTextStyle: {
    fontWeight: '700',
    fontSize: 14,
    paddingVertical: 4,
    color: COLORS.BLACK,
  },
  likeContainerStyle: {paddingHorizontal: 15},
  viewAllCommentStyle: {opacity: 0.7, paddingVertical: 2},
});
