export const ICON_NAME = {
  HOME_FILL: 'home-sharp',
  HOME_UNFILL: 'home-outline',
  SEARCH_FILL: 'search',
  SEARCH_UNFILL: 'ios-search-outline',
  REELS_FILL: 'caret-forward-circle',
  REELS_UNFILL: 'caret-forward-circle-outline',
  HEART_FILL: 'ios-heart',
  HEART_UNFILL: 'ios-heart-outline',
  PERSON_FILL: 'ios-person-circle',
  PERSON_UNFILL: 'ios-person-outline',
  CIRCLE_WITH_PLUS: 'circle-with-plus',
  NAVIGATION: 'navigation',
  VERTICAL_DOT: 'more-vertical',
  HEART: 'heart',
  HEARTO: 'hearto',
  IOS_CHATBUBBLE_OUTLINE: 'ios-chatbubble-outline',
  BOOKMARK: 'bookmark',
};
